server:
  port: ${SERVER_PORT:0}
spring:
  application:
    name: duty-bot-api
  datasource:
    url: jdbc:mysql://${BD_HOST}:${BD_PORT}/${BD_NAME}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    generate-ddl: on
